/* ---------- 第 4 章 ---------- */
CHAPTERS.push({part:"基礎程式設計",id:4,title:"迴圈",lessons:[
 {id:"4-1",title:"while 迴圈",isNew:"while、條件檢查的時機",
  goal:"while 每一輪開始前都會檢查條件。條件不成立就離開，而且離開時變數會停在「讓條件不成立」的那個值。",
  code:M("int i = 1;","while (i <= 3) {","    cout << i << endl;","    i++;","}",'cout << "迴圈結束，i = " << i << endl;'),input:null,
  predict:"最後一行印出的 i 是 3 還是 4？",
  ask:"打開「追蹤表」，看 i 每一步的變化。"},
 {id:"4-2",title:"for 的執行順序",isNew:"初始化 → 檢查 → 本體 → 更新",
  goal:"for 括號裡的三段不是由左到右各做一次：初始化只做一次，然後「檢查 → 本體 → 更新」一直重複。",
  code:M("for (int i = 0; i < 3; i++) {",'    cout << i << " ";',"}","cout << endl;"),input:null,
  tips:{"for (":"注意程式碼中被標起來的那一小段，看看現在執行到 for 的哪個部分。"},
  ask:"i++ 是在印出之前還是之後執行？"},
 {id:"4-3",title:"讀 n 個數求和",isNew:"組合：cin + 迴圈 + 累加",uses:"cin、for、+=",
  goal:"先讀 n，再用迴圈讀 n 次。每讀一個就加進 sum。sum 一定要先歸零。",
  code:M("int n, x;","int sum = 0;","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> x;","    sum += x;","}","cout << sum << endl;"),input:"4\n3 1 4 1",
  ask:"把 int sum = 0; 改成 int sum; 會怎樣？"},
 {id:"4-4",title:"多筆測資",isNew:"讀到 EOF、每筆要重設",uses:"while (cin >> n)、for、累加",
  goal:"OJ 常常一次給好幾筆測資，用 while (cin >> n) 一直讀到沒有資料。每一筆開始前，該歸零的變數要重新歸零。",
  task:"題目：每筆測資第一個數是 n，接著 n 個整數，輸出它們的和。讀到檔案結尾為止。",
  code:M("int n, x;","int sum = 0;","while (cin >> n) {","    for (int i = 0; i < n; i++) {","        cin >> x;","        sum += x;","    }","    cout << sum << endl;","}"),input:"3\n1 2 3\n2\n5 5\n",expected:"6\n10",
  ask:"第一筆對、第二筆錯。哪一行放錯位置了？改到 AC。"},
 {id:"4-5",title:"差一錯誤",isNew:"< 和 <=、迴圈跑幾次",
  goal:"迴圈從哪裡開始、到哪裡結束、用 < 還是 <=，差一點就差一輪。",
  task:"題目：印出 1 到 5，每個數字一行。",
  code:M("for (int i = 1; i < 5; i++) {","    cout << i << endl;","}"),input:null,expected:"1\n2\n3\n4\n5",
  ask:"有兩種改法可以 AC，你能找到幾種？"},
 {id:"4-6",title:"巢狀迴圈",isNew:"迴圈裡面還有迴圈",uses:"cin、for",
  goal:"外層每跑一輪，內層就從頭跑完一整圈。內層的次數可以跟外層的變數有關。",
  code:M("int n;","cin >> n;","for (int i = 1; i <= n; i++) {","    for (int j = 1; j <= i; j++) {",'        cout << "*";',"    }","    cout << endl;","}"),input:"3",
  ask:"要印出倒三角形（第一行 n 個星星），要改哪裡？"},
 {id:"4-7",title:"break 與 continue",isNew:"跳出迴圈、跳過這一輪",
  goal:"continue 跳過這一輪剩下的部分；break 直接結束整個迴圈。",
  code:M("for (int i = 1; i <= 10; i++) {","    if (i % 3 == 0) continue;","    if (i > 7) break;",'    cout << i << " ";',"}","cout << endl;"),input:null,
  predict:"會印出哪些數字？",
  ask:"把兩個 if 的順序對調，結果會變嗎？"}
]});
