/* ---------- 第 5 章 ---------- */
CHAPTERS.push({part:"基礎程式設計",id:5,title:"一維陣列",lessons:[
 {id:"5-1",title:"陣列是連續的格子",isNew:"陣列、索引從 0 開始",
  goal:"陣列是一排連續的格子，用索引存取，第一格是 [0]。索引可以是任何算出整數的式子。",
  code:M("int a[5] = {10, 20, 30};","a[3] = a[0] + a[1];","int i = 2;","a[i + 2] = a[i] * 2;",'cout << a[3] << " " << a[4] << endl;'),input:null,
  markers:{a:["i"]},
  ask:"注意每一格的位址差多少？為什麼？"},
 {id:"5-2",title:"讀進陣列再反向輸出",isNew:"組合：cin + for + 陣列",uses:"cin、for、陣列索引",
  goal:"用迴圈的變數 i 當索引，就能一格一格把資料讀進陣列，之後想用什麼順序取出都可以。",
  code:M("int n;","int a[10];","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> a[i];","}","for (int i = n - 1; i >= 0; i--) {",'    cout << a[i] << " ";',"}","cout << endl;"),input:"5\n3 1 4 1 5",
  markers:{a:["i"]},
  ask:"為什麼第二個迴圈從 n - 1 開始，而不是 n？"},
 {id:"5-3",title:"陣列越界",isNew:"合法索引 0 ～ n-1",uses:"for、陣列",
  goal:"有 3 格的陣列，合法的索引只有 0、1、2。迴圈條件寫錯一點點就會越界，而真正的 C++ 不會提醒你。",
  code:M("int a[3] = {1, 2, 3};","int sum = 0;","for (int i = 0; i <= 3; i++) {","    sum += a[i];","}","cout << sum << endl;"),input:null,
  markers:{a:["i"]},
  ask:"改哪個符號就能修好？"},
 {id:"5-4",title:"找最大值的陷阱",isNew:"最大值的初始值",uses:"cin、for、陣列、if",
  goal:"找最大值時，mx 的初始值不能隨便設成 0。如果資料全是負數，就會出錯。",
  task:"題目：讀入 n 個整數，輸出最大值。",
  code:M("int n;","int a[10];","cin >> n;","for (int i = 0; i < n; i++) cin >> a[i];","int mx = 0;","for (int i = 0; i < n; i++) {","    if (a[i] > mx) mx = a[i];","}","cout << mx << endl;"),input:"4\n-5 -2 -9 -3",expected:"-2",
  markers:{a:["i"]},
  ask:"mx 的初始值應該設成什麼才安全？改到 AC。"},
 {id:"5-5",title:"計數陣列",isNew:"用值當索引：cnt[x]++",uses:"cin、for、陣列",
  goal:"讀到的數字本身就可以當索引。cnt[x]++ 表示「數字 x 又出現一次」。",
  code:M("int n, x;","int cnt[6] = {0};","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> x;","    cnt[x]++;","}","for (int v = 0; v <= 5; v++) {",'    cout << v << ": " << cnt[v] << endl;',"}"),input:"8\n3 1 3 0 5 3 1 5",
  markers:{cnt:["x","v"]},
  ask:"如果輸入裡出現 6，會發生什麼事？"},
 {id:"5-6",title:"全域陣列與區域陣列",isNew:"全域自動歸零",
  goal:"宣告在 main 外面的全域陣列會自動全部設成 0；main 裡面的區域陣列則是垃圾值。大陣列通常也宣告在外面。",
  code:["#include <iostream>","using namespace std;","","int g[5];","","int main() {","    int l[5];","    g[0] = 1;","    l[0] = 1;",'    cout << g[1] << " " << l[1] << endl;',"    return 0;","}"].join("\n"),input:null,
  ask:"OJ 上開 int a[1000000]，放在 main 裡面和外面有什麼差別？"}
]});
