/* ---------- 第 5 章 ---------- */
CHAPTERS.push({part:"基礎程式設計",id:5,title:"一維陣列",lessons:[
 {id:"5-1",title:"陣列是連續的格子",isNew:"陣列、索引從 0 開始",
  goal:"陣列是一排連續的格子，用索引存取，第一格是 [0]。索引可以是任何算出整數的式子。",
  code:M("int a[5] = {10, 20, 30};","a[3] = a[0] + a[1];","int i = 2;","a[i + 2] = a[i] * 2;",'cout << a[3] << " " << a[4] << endl;'),input:null,
  markers:{a:["i"]},
  ask:"注意每一格的位址差多少？為什麼？"},
 {id:"5-2",title:"讀進陣列再反向輸出",isNew:"組合：cin + for + 陣列",uses:"cin、for、陣列索引",
  goal:"用迴圈的變數 i 當索引，就能一格一格把資料讀進陣列，之後想用什麼順序取出都可以。",
  code:M("int n;","int a[10];","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> a[i];","}","for (int i = n - 1; i >= 0; i--) {",'    cout << a[i] << " ";',"}","cout << endl;"),input:"5\n3 1 4 1 5",
  markers:{a:["i"]},
  ask:"為什麼第二個迴圈從 n - 1 開始，而不是 n？"},
 {id:"5-3",title:"陣列越界",isNew:"合法索引 0 ～ n-1",uses:"for、陣列",
  goal:"有 3 格的陣列，合法的索引只有 0、1、2。迴圈條件寫錯一點點就會越界，而真正的 C++ 不會提醒你。",
  code:M("int a[3] = {1, 2, 3};","int sum = 0;","for (int i = 0; i <= 3; i++) {","    sum += a[i];","}","cout << sum << endl;"),input:null,
  markers:{a:["i"]},
  ask:"改哪個符號就能修好？"},
 {id:"5-4",title:"找最大值的陷阱",isNew:"最大值的初始值",uses:"cin、for、陣列、if",
  goal:"找最大值時，mx 的初始值不能隨便設成 0。如果資料全是負數，就會出錯。",
  task:"題目：讀入 n 個整數，輸出最大值。",
  code:M("int n;","int a[10];","cin >> n;","for (int i = 0; i < n; i++) cin >> a[i];","int mx = 0;","for (int i = 0; i < n; i++) {","    if (a[i] > mx) mx = a[i];","}","cout << mx << endl;"),input:"4\n-5 -2 -9 -3",expected:"-2",
  markers:{a:["i"]},
  ask:"mx 的初始值應該設成什麼才安全？改到 AC。"},
 {id:"5-5",title:"計數陣列",isNew:"用值當索引：cnt[x]++",uses:"cin、for、陣列",
  goal:"讀到的數字本身就可以當索引。cnt[x]++ 表示「數字 x 又出現一次」。",
  code:M("int n, x;","int cnt[6] = {0};","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> x;","    cnt[x]++;","}","for (int v = 0; v <= 5; v++) {",'    cout << v << ": " << cnt[v] << endl;',"}"),input:"8\n3 1 3 0 5 3 1 5",
  markers:{cnt:["x","v"]},
  ask:"如果輸入裡出現 6，會發生什麼事？"},
 {id:"5-6",title:"全域陣列與區域陣列",isNew:"全域自動歸零",
  goal:"宣告在 main 外面的全域陣列會自動全部設成 0；main 裡面的區域陣列則是垃圾值。大陣列通常也宣告在外面。",
  code:["#include <iostream>","using namespace std;","","int g[5];","","int main() {","    int l[5];","    g[0] = 1;","    l[0] = 1;",'    cout << g[1] << " " << l[1] << endl;',"    return 0;","}"].join("\n"),input:null,
  ask:"OJ 上開 int a[1000000]，放在 main 裡面和外面有什麼差別？"},
 {id:"5-7",title:"vector：會自己長大的陣列",isNew:"push_back 在後面加一個、size() 問有幾個",uses:"陣列、for",
  goal:"陣列宣告時就要決定大小，之後不能變。#include <vector> 之後可以用 vector：一開始可以是空的，用 push_back 在最後面加一個，它就自己長大一格。\n用法跟陣列很像：v[i] 拿第 i 個（從 0 開始），v.size() 問現在有幾個。看右邊記憶體區，每次 push_back 都會多長一格。",
  code:M("vector<int> v;  // 一開始是空的，不用先決定大小","int i;          // 第幾個","","v.push_back(10);","v.push_back(20);","v.push_back(30);","cout << v.size() << endl;","for (i = 0; i < v.size(); i++) {","    cout << v[i] << \" \";","}","cout << endl;").replace("#include <iostream>","#include <iostream>\n#include <vector>"),input:null,markers:{"v": ["i"]},
  predict:"三次 push_back 之後，v.size() 是多少？v[0] 是哪一個數字？",
  ask:"在最後加一行 cout << v[3] << endl; 會怎樣？vector 會因為你用到 v[3] 就自己變大嗎？"},
 {id:"5-8",title:"vector 的幾種宣告方式",isNew:"空的、給大小、給大小和初始值、用 { } 給值",
  goal:"vector 有幾種常見的宣告方式：\nvector<int> a;：空的，0 個。\nvector<int> b(3);：一開始就有 3 個，都是 0。\nvector<int> c(3, 7);：3 個，每一個都是 7。\nvector<int> d = {1, 2, 3};：直接放進 1、2、3。\n不管用哪一種，之後都還可以 push_back 繼續加。",
  code:M("vector<int> a;             // 空的","vector<int> b(3);          // 3 個，都是 0","vector<int> c(3, 7);       // 3 個，都是 7","vector<int> d = {1, 2, 3};  // 直接放進 1、2、3","","c.push_back(8);","cout << a.size() << \" \" << b.size() << \" \" << c.size() << \" \" << d.size() << endl;","cout << b[0] << \" \" << c[3] << \" \" << d[2] << endl;").replace("#include <iostream>","#include <iostream>\n#include <vector>"),input:null,
  predict:"c.push_back(8); 之後，四個 vector 各有幾個？",
  ask:"陣列 int x[3]; 沒給值的時候是垃圾值，vector<int> b(3); 呢？看看記憶體區。"},
 {id:"5-9",title:"讀 n 個數字放進 vector",isNew:"cin 讀一個、push_back 放一個",uses:"cin、for",
  goal:"很多題目會先給 n，再給 n 個數字。用陣列要先猜一個夠大的大小；用 vector 就不用猜：讀一個數字，就 push_back 一個。全部讀完以後，v.size() 剛好就是 n。",
  code:M("vector<int> v;  // 存讀進來的數字","int n;          // 有幾個數字","int i;          // 第幾個","int x;          // 這一次讀到的數字","","cin >> n;","for (i = 0; i < n; i++) {","    cin >> x;","    v.push_back(x);","}","cout << \"共 \" << v.size() << \" 個，最後一個是 \" << v.back() << endl;").replace("#include <iostream>","#include <iostream>\n#include <vector>"),input:"4\n3 1 4 1",
  predict:"輸入 4 和 3 1 4 1，v 最後長什麼樣子？v.back() 是什麼？",
  ask:"把 n 改成 10，再多打幾個數字。程式需要改哪裡嗎？用陣列的話呢？"},
 {id:"5-10",title:"for (int x : v)：一個一個拿出來",isNew:"範圍 for：依序拿出每一個元素，不用自己管索引",uses:"vector、for",
  goal:"只是要「依序看每一個」的時候，可以用範圍 for：for (int x : v) 的意思是「從 v 的第一個開始，每次拿一個複製到 x」，不用自己寫 i、也不用寫 v.size()。陣列和字串也可以這樣用。\n注意：x 是複製出來的一份，改 x 不會改到 v 裡面的值。",
  code:M("vector<int> v = {3, 1, 4, 1, 5};  // 一組數字","int sum = 0;                     // 總和，一開始 0","","for (int x : v) {","    sum = sum + x;","    x = 0;  // 改的是複製出來的 x","}","cout << sum << \" \" << v[0] << endl;").replace("#include <iostream>","#include <iostream>\n#include <vector>"),input:null,
  predict:"x = 0; 這一行會把 v 裡面的數字改成 0 嗎？最後印出什麼？",
  ask:"如果想要知道每一個是第幾個（例如印出「第 2 個是 4」），用範圍 for 方便嗎？什麼時候還是要用 i？"}
]});
