/* ---------- 第 6 章 字串：從 char 陣列到 <string> ---------- */
// 用到 string 的課，程式開頭要多 #include <string>
const MS=(...body)=>M(...body).replace("#include <iostream>","#include <iostream>\n#include <string>");
CHAPTERS.push({part:"進階程式設計",id:6,title:"字串",lessons:[
 {id:"6-1",title:"字元陣列：很多個 char 排在一起",isNew:"char 陣列，一格放一個字元",
  goal:"一個 char 只能放一個字元。想存一個單字，就用 char 陣列：每一格放一個字元，連續排在記憶體裡。",
  code:M("char word[5] = {'H', 'e', 'l', 'l', 'o'};  // 5 個字元，一格放一個","int i;                                      // 迴圈的計數器，第幾格","","for (i = 0; i < 5; i++) {","    cout << word[i];","}","cout << endl;"),input:null,markers:{"word": ["i"]},
  predict:"word 在記憶體裡佔了幾個 byte？",
  ask:"把 word[0] 改成 'J'，會印出什麼？按「改改看」試試。"},
 {id:"6-2",title:"'\\0'：字串在哪裡結束",isNew:"字串結尾的 '\\0'、用雙引號給初始值",
  goal:"char 陣列不知道自己裝了幾個字，所以 C++ 規定：字串的最後要放一個 '\\0'（數值是 0 的字元）當作結尾。用雙引號給值時會自動補上 '\\0'；cout 印 char 陣列時，會一路印到 '\\0' 才停。",
  code:M("char s[8] = \"Hi\";  // 8 格：'H'、'i'，後面全部是 '\\0'","","cout << s << endl;","s[2] = '!';","cout << s << endl;","s[1] = '\\0';","cout << s << endl;"),input:null,
  predict:"最後一個 cout 會印出什麼？s[2] 的 '!' 還在嗎？",
  ask:"\"Hi\" 只有 2 個字，為什麼 char s[2] = \"Hi\"; 會出錯？改改看。"},
 {id:"6-3",title:"cin 讀進字元陣列",isNew:"cin >> 自動補 '\\0'、數到 '\\0' 就是長度",
  goal:"cin >> 會把一個單字放進 char 陣列，最後自動補上 '\\0'。想知道有幾個字，就從第 0 格往後數，數到 '\\0' 為止。陣列要留一格給 '\\0'，所以 10 格最多只能放 9 個字。",
  code:M("char name[10];  // 最多放 9 個字，加上結尾的 '\\0'","int len = 0;    // 名字有幾個字，一開始 0","","cin >> name;","while (name[len] != '\\0') {","    len = len + 1;","}","cout << name << \" 有 \" << len << \" 個字\" << endl;"),input:"Sinyi",markers:{"name": ["len"]},
  predict:"讀進 Sinyi 之後，name[5] 是什麼？",
  ask:"把輸入改成 Programming（11 個字），會發生什麼事？"},
 {id:"6-4",title:"字元運算：小寫變大寫",isNew:"字元可以加減：c - 'a' + 'A'",
  goal:"char 其實是數字（ASCII 碼）。小寫 'a'～'z' 是連續的，大寫 'A'～'Z' 也是。所以 c - 'a' 就是「第幾個字母」，再加上 'A' 就是對應的大寫字母。",
  code:M("char word[20];  // 輸入的單字","int i;          // 迴圈的計數器，第幾格","","cin >> word;","for (i = 0; word[i] != '\\0'; i++) {","    if (word[i] >= 'a' && word[i] <= 'z') {","        word[i] = word[i] - 'a' + 'A';","    }","}","cout << word << endl;"),input:"Hello",markers:{"word": ["i"]},
  predict:"'e' - 'a' + 'A' 算出來是哪個字元？",
  ask:"要改成「大寫變小寫」，第 10 行和第 11 行要怎麼改？"},
 {id:"6-5",title:"<string>：會自己調整長度的字串",isNew:"#include <string>、+ 接字串、s.length()",
  goal:"char 陣列要先決定幾格，還要自己顧好 '\\0'。#include <string> 之後可以用 string：不用先決定大小，長度會自己調整；用 + 就能把字串接起來；用 s.length() 問它有幾個字。",
  code:MS("string s = \"Hi\";  // 不用先決定要幾格","string t;         // 沒給值就是空字串","","cout << s << \" 長度 \" << s.length() << endl;","s = s + \"!!\";","cout << s << \" 長度 \" << s.length() << endl;","t = s + \" CK\";","cout << t << endl;"),input:null,
  predict:"s = s + \"!!\"; 執行完，s 的長度是多少？",
  ask:"char 陣列可以用 + 接起來嗎？跟 6-2 比較看看，哪一種比較方便？"},
 {id:"6-6",title:"string 也能用 s[i]",isNew:"s[i] 拿到第 i 個字元、搭配 s.length() 走訪",
  goal:"string 跟陣列一樣，可以用 s[i] 拿到第 i 個字元（從 0 開始）。搭配 s.length()，就能用迴圈一個字元一個字元檢查。",
  code:MS("string s;      // 輸入的單字","int i;         // 迴圈的計數器，第幾個字元","int count = 0; // 母音有幾個，一開始 0","","cin >> s;","for (i = 0; i < s.length(); i++) {","    if (s[i] == 'a' || s[i] == 'e' || s[i] == 'i' || s[i] == 'o' || s[i] == 'u') {","        count = count + 1;","    }","}","cout << count << endl;"),input:"education",markers:{"s": ["i"]},
  predict:"education 有幾個母音？迴圈會轉幾圈？",
  ask:"改成把每個母音換成 '*' 再印出 s，要怎麼寫？"},
 {id:"6-7",title:"cin >> 和 getline",isNew:"getline 讀一整行、cin >> 留下的換行",
  goal:"cin >> 讀到空白或換行就停，而且「不會」把後面的換行拿走。getline 會讀一整行（空白也算），讀到換行為止。所以 cin >> 後面直接接 getline，getline 會先撞到上一行留下的換行，讀到一個空字串。",
  code:MS("int age;      // 年齡（第一行）","string name;  // 全名，中間有空白（第二行）","","cin >> age;","getline(cin, name);","cout << \"age = \" << age << endl;","cout << \"name = [\" << name << \"]\" << endl;"),input:"15\nLin Sinyi",
  predict:"name 會讀到 Lin Sinyi 嗎？",
  ask:"在 getline 前面加一行 cin.ignore(); 再執行一次。這一行把什麼丟掉了？"}
]});
