/* ---------- 第 11 章 struct 與鏈結串列：學完指標，把資料綁在一起，再用指標串起來 ---------- */
// struct 定義寫在 main 上面，用第 8 章的 FN(定義們, ...main 裡的程式)
const STU=["struct Student {","    string name;  // 名字","    int score;    // 分數","};"];
const NODE=["struct Node {","    int data;    // 這個節點存的資料","    Node *next;  // 下一個節點的位址","};"];
// 串好的三個節點 10 → 20 → 30
const THREE=["Node *head = new Node{10, nullptr};  // 串列的第一個節點","head->next = new Node{20, nullptr};","head->next->next = new Node{30, nullptr};"];
CHAPTERS.push({part:"進階程式設計",id:11,title:"struct 與鏈結串列",lessons:[
 {id:"11-1",title:"struct：把欄位綁在一起",isNew:"struct 定義新型別、變數.欄位",
  goal:"一個學生有名字也有分數，用兩個變數分開放很容易亂掉。struct 可以把它們綁成一種新的型別：struct Student { ... }; 定義了 Student，裡面的 name、score 叫做「欄位」。用「變數.欄位」來存取，例如 a.score。\n注意：struct 定義的 } 後面一定要加分號。",
  code:FN(STU,"Student a;  // 一個學生：名字和分數綁在一起","","a.name = \"Amy\";","a.score = 90;","cout << a.name << \" \" << a.score << endl;"),input:null,
  predict:"a 剛宣告完，a.name 和 a.score 分別是什麼？",
  ask:"把 struct 定義最後的分號刪掉，會出現什麼錯誤？"},
 {id:"11-2",title:"初始值與整個複製",isNew:"{ } 照欄位順序給值、b = a 整個複製",
  goal:"宣告時可以用 { } 照「欄位的順序」給值。struct 可以用 = 整個複製：每個欄位都複製一份。複製完，a 和 b 還是兩塊不同的記憶體，改 b 不會影響 a。\n但是 struct 不能直接用 == 或 < 比較，C++ 不知道你想比哪一個欄位，要自己指定，例如 a.score < b.score。",
  code:FN(STU,"Student a = {\"Amy\", 90};  // 照欄位順序：name、score","Student b;                 // 另一個學生","","b = a;","b.score = 60;","cout << a.name << \" \" << a.score << endl;","cout << b.name << \" \" << b.score << endl;"),input:null,
  predict:"b.score = 60; 之後，a.score 是多少？",
  ask:"加一行 if (a < b) cout << \"a 比較小\"; 會怎樣？要改成比較什麼才對？"},
 {id:"11-3",title:"struct 陣列",isNew:"a[i].score：第 i 個學生的分數",uses:"cin、for、if、陣列",
  goal:"struct 也可以開成陣列：a[i] 是第 i 個學生，a[i].score 是他的分數。名字和分數一直綁在一起，找到最高分的那一格，名字就跟著找到了。",
  task:"題目：輸入 n 位學生的名字和分數，輸出最高分的學生名字。",
  code:FN(STU,"Student a[5];  // 最多 5 位學生","int n;         // 學生人數","int best = 0;  // 目前最高分的是第幾個學生","","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> a[i].name >> a[i].score;","}","for (int i = 1; i < n; i++) {","    if (a[i].score > a[best].score) {","        best = i;","    }","}","cout << a[best].name << endl;"),
  tests:[{input:"3\nAmy 70\nBob 95\nCat 80",output:"Bob",note:""},{input:"2\nDan 60\nEve 88",output:"Eve",note:""}],
  markers:{a:["i","best"]},
  ask:"如果改用兩個陣列 string name[5]、int score[5] 來寫，要怎麼寫？哪一種比較不容易出錯？"},
 {id:"11-4",title:"指向 struct 的指標",isNew:"Student *p、p->score 就是 (*p).score",uses:"指標、傳址",
  goal:"指標也可以指向 struct。p 存 a 的位址，*p 就是 a，所以 (*p).score 就是 a.score。這種寫法太常用了，C++ 給它一個簡寫：p->score（箭頭）。\n把 struct 的位址傳進函式，函式就能改到外面的 struct，跟第 10 章的傳址一樣。右邊記憶體區的箭頭就是「指標指向誰」。",
  code:FN([...STU,"","void addBonus(Student *s) {","    s->score = s->score + 10;","}"],"Student a = {\"Amy\", 70};  // 一個學生","Student *p;                // 指向 Student 的指標","","p = &a;","(*p).score = 80;","p->score = 85;","addBonus(&a);","cout << a.score << endl;"),input:null,
  predict:"最後印出的 a.score 是多少？",
  ask:"把 (*p).score 的括號拿掉，寫成 *p.score，會發生什麼事？"},
 {id:"11-5",title:"節點與 new",isNew:"Node *next、new 借空間、delete 歸還",uses:"struct、指標",
  goal:"鏈結串列（linked list）的每一格叫做「節點」：data 放資料，next 放「下一個節點的位址」。next 的型別是 Node*，struct 裡可以放指向自己這種 struct 的指標。\nnew Node 會在 heap 借一塊 Node 大小的空間，把位址交回來。這塊空間沒有名字，只能靠指標找到它，所以要用 p->data 存取。用完用 delete 還回去。\n陣列一開始就要決定大小；new 則是需要的時候再一個一個借。",
  code:FN(NODE,"Node *p;  // 指向一個節點的指標","","p = new Node;","p->data = 5;","p->next = nullptr;  // 後面沒有了","cout << p->data << endl;","delete p;","p = nullptr;"),input:null,
  predict:"new Node 剛借來的時候，data 和 next 是什麼？",
  ask:"把 p = nullptr; 刪掉，在最後加一行 cout << p->data; 會發生什麼事？"},
 {id:"11-6",title:"把節點串起來",isNew:"next 指向下一個節點、nullptr 代表結尾",uses:"struct、指標、new",
  goal:"new Node{10, nullptr} 借一個節點，同時照欄位順序放進 data = 10、next = nullptr。\nhead->next = new Node{20, nullptr}; 把第二個節點的位址放進第一個節點的 next，兩個節點就接起來了；head->next->next 則是第二個節點的 next。最後一個節點的 next 是 nullptr，表示「到底了」。\n這樣串起來就是鏈結串列。只要記住第一個節點的位址（head），就能沿著箭頭找到全部。看右邊 heap 裡的箭頭。",
  code:FN(NODE,...THREE,"","cout << head->data << endl;","cout << head->next->data << endl;","cout << head->next->next->data << endl;"),input:null,
  predict:"head->next->next->data 是多少？",
  ask:"head->next->next->next 是什麼？如果再多寫一個 ->data 會怎樣？"},
 {id:"11-7",title:"走訪鏈結串列",isNew:"p = p->next：走到下一個節點",uses:"while、指標",
  goal:"不知道串列有多長的時候，用一個指標 p 從 head 出發，p = p->next 就是「沿著箭頭走到下一個節點」，走到 nullptr 就代表走完了。這是鏈結串列最重要的一個迴圈。",
  code:FN(NODE,...THREE,"Node *p;      // 走訪用的指標","int sum = 0;  // 加總","","p = head;","while (p != nullptr) {","    cout << p->data << \" \";","    sum = sum + p->data;","    p = p->next;","}","cout << endl << sum << endl;"),input:null,
  predict:"迴圈會跑幾輪？最後一輪結束時，p 是什麼？",
  ask:"把 p = p->next; 刪掉會怎樣？把條件改成 p->next != nullptr 呢？"},
 {id:"11-8",title:"插在最前面",isNew:"nd->next = head; head = nd;",uses:"cin、for、new、指標",
  goal:"在串列最前面加一個節點只要兩步：新節點的 next 先指向原本的第一個（head），再讓 head 改成新節點。\n順序很重要：如果先改 head，原本的串列就沒有人記得了。",
  task:"題目：輸入 n 和 n 個整數，每讀到一個就插在串列的最前面，最後從頭印出整個串列。",
  code:FN(NODE,"Node *head = nullptr;  // 一開始是空的串列","Node *nd;              // 新借的節點","Node *p;               // 走訪用的指標","int n, x;              // 個數、讀到的數","","cin >> n;","for (int i = 0; i < n; i++) {","    cin >> x;","    nd = new Node;","    nd->data = x;","    nd->next = head;","    head = nd;","}","for (p = head; p != nullptr; p = p->next) {","    cout << p->data << \" \";","}","cout << endl;"),
  tests:[{input:"3\n10 20 30",output:"30 20 10",note:"每次都插在最前面，所以順序會反過來"},{input:"1\n7",output:"7",note:""}],
  predict:"印出來的順序跟輸入的順序一樣嗎？",
  ask:"把 nd->next = head; 和 head = nd; 兩行對調，會印出什麼？為什麼？"},
 {id:"11-9",title:"刪掉第一個節點",isNew:"先記住、再移動 head、最後 delete",uses:"new、delete、指標",
  goal:"刪掉第一個節點：先用 old 記住它，head 往後移到下一個，最後 delete old 把空間還回去。\n如果直接 delete head，就再也拿不到 head->next 了。",
  code:FN(NODE,...THREE,"Node *old;  // 暫時記住要刪掉的節點","","old = head;","head = head->next;","delete old;","for (Node *p = head; p != nullptr; p = p->next) {","    cout << p->data << \" \";","}","cout << endl;"),input:null,
  predict:"delete old 之後，old 這個指標還存著什麼？還能用嗎？",
  ask:"把三行改成 delete head; head = head->next; 會發生什麼事？"}
]});
