/* ---------- 第 12 章 Stack：先用陣列自己做，再看 C++ 內建的 stack ---------- */
const H12=(head,...body)=>M(...body).replace("#include <iostream>","#include <iostream>\n"+head);
CHAPTERS.push({part:"進階程式設計",id:12,title:"Stack",lessons:[
 {id:"12-1",title:"用陣列做一個 stack",isNew:"stack 像一疊盤子：push 放上去、pop 拿最上面",
  goal:"stack（堆疊）像一疊盤子：只能從最上面放（push），也只能從最上面拿（pop）。用陣列來做，再加一個 top 記住「最上面那一個在第幾格」。top 是 -1 代表空的。",
  code:M("int st[5];     // 放資料的陣列，最多 5 個","int top = -1;  // 最上面那一個在第幾格，-1 代表空的","","top = top + 1;  // push 10","st[top] = 10;","top = top + 1;  // push 20","st[top] = 20;","top = top + 1;  // push 30","st[top] = 30;","while (top >= 0) {","    cout << st[top] << endl;  // 看最上面那一個","    top = top - 1;            // pop：top 往下移一格","}"),input:null,markers:{"st": ["top"]},
  predict:"放進去的順序是 10、20、30，印出來的順序是什麼？",
  ask:"pop 之後，st[2] 裡面的 30 還在記憶體裡嗎？為什麼不用把它清掉？"},
 {id:"12-2",title:"後進先出",isNew:"LIFO：最後放進去的最先拿出來",
  goal:"stack 的規則叫做「後進先出」（LIFO）：最後 push 進去的，最先被 pop 出來。這個程式讀一串數字：大於 0 就 push，讀到 0 就 pop 並印出來。",
  code:M("int st[10];    // 放資料的陣列","int top = -1;  // 最上面那一個在第幾格，-1 代表空的","int x;         // 讀進來的數字：大於 0 就 push，0 就 pop","","while (cin >> x) {","    if (x > 0) {","        top = top + 1;","        st[top] = x;","    } else {","        cout << st[top] << \" \";","        top = top - 1;","    }","}","cout << endl;"),input:"1 2 0 3 0 0",markers:{"st": ["top"]},
  predict:"輸入 1 2 0 3 0 0，會印出哪三個數字？",
  ask:"把輸入改成 1 0 0，第二個 0 要 pop 的時候會發生什麼事？"},
 {id:"12-3",title:"空的不能 pop、滿的不能 push",isNew:"pop 前檢查 top == -1、push 前檢查滿了沒",
  goal:"stack 空的時候（top 是 -1）不能 pop，不然會讀到 st[-1]；陣列滿了也不能再 push。所以 push 和 pop 之前都要先檢查。",
  code:M("int st[3];     // 放資料的陣列，只有 3 格","int top = -1;  // 最上面那一個在第幾格，-1 代表空的","int x;         // 讀進來的數字：大於 0 就 push，0 就 pop","","while (cin >> x) {","    if (x > 0) {","        if (top == 2) {","            cout << \"滿了 \";","        } else {","            top = top + 1;","            st[top] = x;","        }","    } else if (top == -1) {","        cout << \"空的 \";","    } else {","        cout << st[top] << \" \";","        top = top - 1;","    }","}","cout << endl;"),input:"5 0 0 1 2 3 4",markers:{"st": ["top"]},
  predict:"輸入 5 0 0 1 2 3 4，會印出什麼？",
  ask:"「滿了」的條件為什麼是 top == 2，不是 top == 3？"},
 {id:"12-4",title:"C++ 內建的 stack",isNew:"#include <stack>：push、pop、top、empty、size",
  goal:"C++ 已經幫你做好 stack 了：#include <stack> 之後，用 stack<int> 宣告，就不用自己管陣列和 top。st.push(x) 放上去、st.top() 看最上面、st.pop() 拿掉最上面、st.empty() 問是不是空的、st.size() 問有幾個。",
  code:H12("#include <stack>","stack<int> st;  // C++ 內建的 stack，不用自己管 top","int x;          // 讀進來的數字","","while (cin >> x) {","    st.push(x);","}","cout << \"共 \" << st.size() << \" 個\" << endl;","while (!st.empty()) {","    cout << st.top() << \" \";","    st.pop();","}","cout << endl;"),input:"1 2 3",
  predict:"輸入 1 2 3，第二行會印出什麼順序？",
  ask:"把 while (!st.empty()) 拿掉，直接連續 pop 四次，會發生什麼事？跟 12-2 用陣列做的比較看看。"},
 {id:"12-5",title:"追蹤 push / pop",isNew:"一串操作之後印出什麼？先畫再對答案",
  goal:"APCS 觀念題很常出這一型：給你一串 push、pop，問最後印出什麼。訣竅是在紙上畫一個直的 stack，每做一個操作就更新一次，只看最上面那一個。\n先自己畫完、寫下三行輸出，再按「下一步」一步一步對答案。",
  code:H12("#include <stack>","stack<int> st;  // 一個空的 stack","","st.push(5);","st.push(8);","cout << st.top() << endl;","st.pop();","st.push(3);","st.push(7);","st.pop();","cout << st.top() << endl;","cout << st.size() << endl;"),input:null,
  predict:"三行 cout 分別會印出什麼？",
  ask:"把第二個 st.pop(); 拿掉，答案會變成什麼？"},
 {id:"12-6",title:"遞迴其實就是 stack",isNew:"自己用 stack 做出遞迴：先一路往下記，再一層一層回來",
  goal:"第 9 章「呼叫堆疊長高再縮回」的 fact(4)，電腦其實就是用一個 stack 在記每一層還沒算完的 n。\n這支程式不用遞迴，自己用一個 stack 做同樣的事：第一個迴圈像「往下呼叫」，把每一層的 n 放進去；第二個迴圈像「一層一層回來」，從最上面拿出來乘。對照第 9 章記憶體區一層一層的 fact，就是這裡的 stack。",
  code:H12("#include <stack>","stack<int> st;  // 記住每一層還沒算完的 n","int n = 4;      // 要算 4!","int ans = 1;    // 答案，一開始 1","","while (n > 1) {  // 像遞迴「往下呼叫」","    st.push(n);","    n = n - 1;","}","while (!st.empty()) {  // 像遞迴「一層一層回來」","    ans = ans * st.top();","    st.pop();","}","cout << ans << endl;"),input:null,
  predict:"第一個迴圈結束的時候，stack 裡由上到下是哪些數字？",
  ask:"打開第 9 章的 9-2，比較兩邊的記憶體區：哪裡長得一樣？"}
]});
