/* ---------- 第 13 章 Queue：先用陣列自己做，再看環狀佇列和 C++ 內建的 queue ---------- */
const H13=(head,...body)=>M(...body).replace("#include <iostream>","#include <iostream>\n"+head);
CHAPTERS.push({part:"進階程式設計",id:13,title:"Queue",lessons:[
 {id:"13-1",title:"用陣列做一個 queue",isNew:"queue 像排隊：從後面進來、從前面出去",
  goal:"queue（佇列）像排隊：新來的排在最後面，最前面的先離開。用陣列來做，需要兩個位置：\nfront：最前面那一個在第幾格（下一個要出去的）。\nrear：下一個進來的要放在第幾格。\n進隊就是放在 q[rear]，rear 往後一格；出隊就是拿 q[front]，front 往後一格。front 等於 rear 代表沒有東西了。",
  code:M("int q[5];       // 放資料的陣列，最多 5 個","int front = 0;  // 最前面那一個在第幾格","int rear = 0;   // 下一個進來的要放在第幾格","","q[rear] = 10;  // 進隊 10","rear = rear + 1;","q[rear] = 20;  // 進隊 20","rear = rear + 1;","q[rear] = 30;  // 進隊 30","rear = rear + 1;","while (front < rear) {","    cout << q[front] << endl;  // 出隊：拿最前面那一個","    front = front + 1;","}"),input:null,markers:{"q": ["front", "rear"]},
  predict:"放進去的順序是 10、20、30，印出來的順序是什麼？跟 12-1 的 stack 一樣嗎？",
  ask:"出隊以後，q[0] 裡面的 10 還在記憶體裡嗎？front 和 rear 最後各是多少？"},
 {id:"13-2",title:"先進先出",isNew:"FIFO：最先進來的最先出去",
  goal:"queue 的規則叫做「先進先出」（FIFO）：最先進來的，最先出去。這個程式跟 12-2 一樣讀一串數字：大於 0 就進隊，讀到 0 就出隊並印出來。用同一組輸入，比較 stack 和 queue 印出來的順序。",
  code:M("int q[10];      // 放資料的陣列","int front = 0;  // 最前面那一個在第幾格","int rear = 0;   // 下一個進來的要放在第幾格","int x;          // 讀進來的數字：大於 0 就進隊，0 就出隊","","while (cin >> x) {","    if (x > 0) {","        q[rear] = x;","        rear = rear + 1;","    } else {","        cout << q[front] << \" \";","        front = front + 1;","    }","}","cout << endl;"),input:"1 2 0 3 0 0",markers:{"q": ["front", "rear"]},
  predict:"輸入 1 2 0 3 0 0，會印出哪三個數字？12-2 的 stack 印出的是 2 3 1。",
  ask:"把輸入改成 1 0 0，第二個 0 要出隊的時候會發生什麼事？"},
 {id:"13-3",title:"空的、滿的、浪費的空間",isNew:"rear 走到最後就說滿了，前面空出來的格子卻用不到",
  goal:"出隊之前要檢查是不是空的（front 等於 rear）；進隊之前要檢查是不是滿了（rear 等於陣列的格數）。\n可是這樣有個問題：出隊以後 front 往後走，前面空出來的格子再也用不到。rear 一走到最後就說「滿了」，明明前面還有空位，這叫做「假溢位」。下一課的環狀佇列就是要解決這個問題。",
  code:M("int q[3];       // 放資料的陣列，只有 3 格","int front = 0;  // 最前面那一個在第幾格","int rear = 0;   // 下一個進來的要放在第幾格","int x;          // 讀進來的數字：大於 0 就進隊，0 就出隊","","while (cin >> x) {","    if (x > 0) {","        if (rear == 3) {","            cout << \"滿了 \";","        } else {","            q[rear] = x;","            rear = rear + 1;","        }","    } else if (front == rear) {","        cout << \"空的 \";","    } else {","        cout << q[front] << \" \";","        front = front + 1;","    }","}","cout << endl;"),input:"1 2 3 0 0 4",markers:{"q": ["front", "rear"]},
  predict:"輸入 1 2 3 0 0 4，最後的 4 放得進去嗎？那時候 queue 裡面其實有幾個數字？",
  ask:"看最後一步的記憶體區：q[0]、q[1] 是空出來的嗎？為什麼還是說滿了？"},
 {id:"13-4",title:"環狀佇列",isNew:"rear = (rear + 1) % 3：走到最後一格就繞回第 0 格",
  goal:"把陣列想成頭尾相接的一個圓圈：front 或 rear 走到最後一格，下一步就繞回第 0 格，前面空出來的格子就能再用。\n做法是用 % 取餘數：rear = (rear + 1) % 3，2 的下一格是 (2 + 1) % 3 = 0。\n這時候 front 等於 rear 可能是空的、也可能是滿的，所以多用一個 count 記住現在有幾個。",
  code:M("int q[3];       // 放資料的陣列，只有 3 格","int front = 0;  // 最前面那一個在第幾格","int rear = 0;   // 下一個進來的要放在第幾格","int count = 0;  // 現在有幾個，一開始 0","int x;          // 讀進來的數字：大於 0 就進隊，0 就出隊","","while (cin >> x) {","    if (x > 0) {","        if (count == 3) {","            cout << \"滿了 \";","        } else {","            q[rear] = x;","            rear = (rear + 1) % 3;  // 走到最後一格就繞回第 0 格","            count = count + 1;","        }","    } else if (count == 0) {","        cout << \"空的 \";","    } else {","        cout << q[front] << \" \";","        front = (front + 1) % 3;","        count = count - 1;","    }","}","cout << endl;"),input:"1 2 3 0 0 4 5 6 0 0 0",markers:{"q": ["front", "rear"]},
  predict:"跟上一課一樣先放 1 2 3、再拿走兩個，這次 4 放在哪一格？",
  ask:"6 為什麼放不進去？這時候 front 和 rear 是不是一樣？只看 front 和 rear 分得出是空的還是滿的嗎？"},
 {id:"13-5",title:"C++ 內建的 queue",isNew:"#include <queue>：push、pop、front、back、empty、size",
  goal:"C++ 已經幫你做好 queue 了：#include <queue> 之後，用 queue<int> 宣告，就不用自己管陣列、front 和 rear，也不用擔心假溢位。\nq.push(x) 排到最後面、q.front() 看最前面、q.back() 看最後面、q.pop() 拿走最前面、q.empty() 問是不是空的、q.size() 問有幾個。\n注意：queue 沒有 top()，因為它是看「最前面」，不是看「最上面」。",
  code:H13("#include <queue>","queue<int> q;  // C++ 內建的 queue","int x;         // 讀進來的數字","","while (cin >> x) {","    q.push(x);","}","cout << \"共 \" << q.size() << \" 個，最前面 \" << q.front() << \"，最後面 \" << q.back() << endl;","while (!q.empty()) {","    cout << q.front() << \" \";","    q.pop();","}","cout << endl;"),input:"1 2 3",
  predict:"輸入 1 2 3，第二行印出來的順序是什麼？跟 12-4 的 stack 比較看看。",
  ask:"把 q.front() 改成 q.top() 會怎樣？"},
 {id:"13-6",title:"追蹤 push / pop",isNew:"跟 stack 一模一樣的操作，換成 queue 結果不一樣",
  goal:"這一課的操作跟 12-5 一模一樣，只是 stack 換成 queue。push 都是放進去，但 pop 拿走的不一樣：stack 拿走最上面（最後放進去的），queue 拿走最前面（最先放進去的）。\n先在紙上畫一排 queue，每做一個操作就更新一次，寫下三行輸出，再按「下一步」對答案。12-5 的 stack 印出的是 8、3、2。",
  code:H13("#include <queue>","queue<int> q;  // 一個空的 queue","","q.push(5);","q.push(8);","cout << q.front() << endl;","q.pop();","q.push(3);","q.push(7);","q.pop();","cout << q.front() << endl;","cout << q.size() << endl;"),input:null,
  predict:"三行 cout 分別會印出什麼？跟 stack 的 8、3、2 比，哪一行一樣、哪一行不一樣？",
  ask:"把第二個 q.pop(); 拿掉，答案會變成什麼？"},
 {id:"13-7",title:"deque：兩頭都能進出",isNew:"#include <deque>：push_front、push_back、pop_front、pop_back",uses:"queue（13-5）、stack（12-4）",
  goal:"deque（雙向佇列，唸作 deck）兩頭都可以放、都可以拿：push_front、push_back 放進去，pop_front、pop_back 拿出來，front()、back() 看兩頭。\n只用 push_back 和 pop_back，它就像 stack；只用 push_back 和 pop_front，它就像 queue。deque 還可以用 d[i] 看第幾個。",
  code:M("deque<int> d;  // 兩頭都能進出","","d.push_back(2);   // 後面放 2","d.push_back(3);   // 後面放 3","d.push_front(1);  // 前面放 1","cout << d.front() << \" \" << d.back() << endl;","d.pop_back();     // 拿掉最後面","d.push_front(0);  // 前面放 0","cout << d.front() << \" \" << d.back() << \" \" << d.size() << endl;","cout << d[1] << endl;").replace("#include <iostream>","#include <iostream>\n#include <deque>"),input:null,
  predict:"兩行 cout 分別會印出什麼？d[1] 是哪一個？",
  ask:"如果只用 push_back 和 pop_front，d 會像 stack 還是 queue？改改看。"}
]});
