/* ---------- 第 14 章 複雜度與排序：用一維陣列看每一種排序怎麼移動數字（堆積排序先用 2i + 1、2i + 2 的數學關係，不畫樹） ---------- */
CHAPTERS.push({part:"進階程式設計",id:14,title:"複雜度與排序",lessons:[
 {id:"14-1",title:"時間複雜度：數一數做了幾次",isNew:"O(n)、O(n²)：資料變多時，要做的事變多多少",
  goal:"程式快不快，不是看秒數（每台電腦不一樣），而是看「資料有 n 個的時候，大約要做幾次」。\n一層迴圈跑 n 次，叫做 O(n)：n 變 10 倍，次數也變 10 倍。兩層迴圈各跑 n 次，總共 n × n 次，叫做 O(n²)：n 變 10 倍，次數變 100 倍。\n電腦一秒大約只能做 1 億（10⁸）次。題目的 n 如果是 10 萬，O(n²) 就要做 100 億次，一定超過時間，這就是 OJ 上的 TLE（Time Limit Exceeded）。",
  code:M("int n = 10;    // 資料有幾個","int i, j;      // 迴圈用","int one = 0;   // 一層迴圈做了幾次","int two = 0;   // 兩層迴圈做了幾次","","for (i = 0; i < n; i++) {","    one = one + 1;","}","for (i = 0; i < n; i++) {","    for (j = 0; j < n; j++) {","        two = two + 1;","    }","}","cout << \"一層：\" << one << \" 次\" << endl;","cout << \"兩層：\" << two << \" 次\" << endl;"),input:null,
  predict:"n = 10 的時候，one 和 two 分別是多少？",
  ask:"把 n 改成 20，one 和 two 各變成幾倍？如果 n 是 10 萬，two 會是多少？"},
 {id:"14-2",title:"泡沫排序",isNew:"相鄰兩格比一比，大的往後換",uses:"陣列、巢狀 for、交換",
  goal:"泡沫排序：從頭到尾，相鄰的兩格比一比，左邊比右邊大就交換。這樣走一輪，最大的數字就會一路被換到最後面，像泡泡浮上來一樣。\n第 1 輪把最大的放到最後一格，第 2 輪把第二大的放到倒數第二格……所以每一輪要比的範圍都少一格（n - 1 - i）。",
  code:M("int a[6] = {5, 2, 4, 6, 1, 3};  // 要排序的數字","int n = 6;                      // 有幾個","int i, j;                       // i：第幾輪；j：正在比 a[j] 和 a[j + 1]","int t;                          // 交換用","","for (i = 0; i < n - 1; i++) {","    for (j = 0; j < n - 1 - i; j++) {","        if (a[j] > a[j + 1]) {","            t = a[j];","            a[j] = a[j + 1];","            a[j + 1] = t;","        }","    }","}","for (i = 0; i < n; i++) {","    cout << a[i] << \" \";","}","cout << endl;"),input:null,markers:{"a": ["j"]},
  predict:"第 1 輪結束的時候，最後一格是哪個數字？",
  ask:"每一輪比的範圍為什麼是 j < n - 1 - i？改成 j < n - 1，結果會錯嗎？會比較慢嗎？"},
 {id:"14-3",title:"選擇排序",isNew:"每一輪找出最小的，放到最前面",uses:"陣列、巢狀 for",
  goal:"選擇排序：第 i 輪，從 a[i] 到最後面找出最小的那一個（記住它的位置 m），再把它跟 a[i] 交換。這樣前面就一格一格排好。\n跟泡沫排序比：選擇排序每一輪只交換一次。",
  code:M("int a[6] = {5, 2, 4, 6, 1, 3};  // 要排序的數字","int n = 6;                      // 有幾個","int i, j;                       // i：這一輪要放的位置；j：往後找","int m;                          // 目前找到最小的在第幾格","int t;                          // 交換用","","for (i = 0; i < n - 1; i++) {","    m = i;","    for (j = i + 1; j < n; j++) {","        if (a[j] < a[m]) {","            m = j;","        }","    }","    t = a[i];","    a[i] = a[m];","    a[m] = t;","}","for (i = 0; i < n; i++) {","    cout << a[i] << \" \";","}","cout << endl;"),input:null,markers:{"a": ["i", "j", "m"]},
  predict:"第 1 輪會找到哪個數字、放到哪裡？",
  ask:"跟 14-2 比，哪一種交換的次數比較少？看看追蹤表裡 t 被改了幾次。"},
 {id:"14-4",title:"插入排序",isNew:"拿起一個，往前插到對的位置",uses:"陣列、for、while",
  goal:"插入排序像整理撲克牌：左邊的牌已經排好，每次拿起下一張（key），從右往左看，比它大的就往右挪一格，挪到不能挪的時候，把 key 放進空出來的位置。\n如果數字本來就快要排好，插入排序幾乎不用挪，會很快。",
  code:M("int a[6] = {5, 2, 4, 6, 1, 3};  // 要排序的數字","int n = 6;                      // 有幾個","int i, j;                       // i：這一輪拿起的是 a[i]；j：往左比","int key;                        // 拿起來要插進去的數字","","for (i = 1; i < n; i++) {","    key = a[i];","    j = i - 1;","    while (j >= 0 && a[j] > key) {","        a[j + 1] = a[j];  // 比 key 大的往右挪","        j = j - 1;","    }","    a[j + 1] = key;","}","for (i = 0; i < n; i++) {","    cout << a[i] << \" \";","}","cout << endl;"),input:null,markers:{"a": ["i", "j"]},
  predict:"拿起 1 的那一輪，要往右挪幾個數字？",
  ask:"把一開始的數字改成 {1, 2, 3, 4, 6, 5}（幾乎排好了），步數變多還是變少？"},
 {id:"14-5",title:"合併排序",isNew:"切成兩半各自排好，再把兩半合併",uses:"遞迴（第 9 章）、陣列傳進函式",
  goal:"合併排序用的是「分而治之」：\n1. 切：把 a[l] ～ a[r] 從中間切成兩半。\n2. 各自排好：兩半各自再用合併排序（遞迴），切到只剩一個就不用排了。\n3. 合併：兩半都已經排好，各從開頭比一比，小的先放進 tmp，最後再抄回 a。\n看記憶體區的呼叫堆疊：每一層 mergeSort 負責一段，l、mid、r 標在陣列下面。",
  code:FN(["int tmp[6];  // 合併時暫放的陣列","","void mergeSort(int a[], int l, int r) {  // 把 a[l] ～ a[r] 排好","    int mid;      // 中間的位置","    int i, j, k;  // i 走左半、j 走右半、k 放進 tmp","","    if (l >= r) {","        return;  // 只剩一個：已經排好了","    }","    mid = (l + r) / 2;","    mergeSort(a, l, mid);","    mergeSort(a, mid + 1, r);","    i = l;","    j = mid + 1;","    k = l;","    while (i <= mid && j <= r) {","        if (a[i] <= a[j]) {","            tmp[k] = a[i];","            i = i + 1;","        } else {","            tmp[k] = a[j];","            j = j + 1;","        }","        k = k + 1;","    }","    while (i <= mid) {","        tmp[k] = a[i];","        i = i + 1;","        k = k + 1;","    }","    while (j <= r) {","        tmp[k] = a[j];","        j = j + 1;","        k = k + 1;","    }","    for (k = l; k <= r; k++) {","        a[k] = tmp[k];","    }","}"],"int a[6] = {5, 2, 4, 6, 1, 3};  // 要排序的數字","int i;                          // 印出來用","","mergeSort(a, 0, 5);","for (i = 0; i < 6; i++) {","    cout << a[i] << \" \";","}","cout << endl;"),input:null,markers:{"a": ["l", "mid", "r"], "tmp": ["k"]},
  predict:"第一次合併的是哪兩個數字？",
  ask:"呼叫堆疊最多疊幾層 mergeSort？如果有 12 個數字呢？"},
 {id:"14-6",title:"快速排序",isNew:"選一個基準：比它小的放左邊，比它大的放右邊",uses:"遞迴（第 9 章）、陣列傳進函式",
  goal:"快速排序也是分而治之：\n1. 選基準（pivot）：這裡選這一段的最後一個 a[r]。\n2. 分邊：j 從左走到右，遇到比 pivot 小的，就換到左邊的「小區」（i 是小區的最後一格）。走完以後把 pivot 放到小區的後面，它就站在最後排好的位置上了。\n3. 左右兩邊各自再做一次（遞迴）。",
  code:FN(["void quickSort(int a[], int l, int r) {  // 把 a[l] ～ a[r] 排好","    int pivot;  // 基準：這一段的最後一個","    int i;      // 比 pivot 小的區域，最後一格在哪","    int j;      // 正在檢查的位置","    int t;      // 交換用","","    if (l >= r) {","        return;","    }","    pivot = a[r];","    i = l - 1;","    for (j = l; j < r; j++) {","        if (a[j] < pivot) {","            i = i + 1;","            t = a[i];","            a[i] = a[j];","            a[j] = t;","        }","    }","    t = a[i + 1];","    a[i + 1] = a[r];","    a[r] = t;","    quickSort(a, l, i);","    quickSort(a, i + 2, r);","}"],"int a[6] = {5, 2, 4, 6, 1, 3};  // 要排序的數字","int i;                          // 印出來用","","quickSort(a, 0, 5);","for (i = 0; i < 6; i++) {","    cout << a[i] << \" \";","}","cout << endl;"),input:null,markers:{"a": ["i", "j", "r"]},
  predict:"第一次分邊以後，pivot 3 會站在第幾格？",
  ask:"把一開始的數字改成已經排好的 {1, 2, 3, 4, 5, 6}，步數會變多還是變少？為什麼？"},
 {id:"14-7",title:"堆積排序",isNew:"最大的換到最後面，剩下的再整理成堆積",uses:"heap 會在第 16 章「樹」仔細介紹",
  goal:"堆積排序用到一種叫做「最大堆積」（heap）的結構：把陣列整理成「最大的一定在 a[0]」的樣子。heap 其實是一種「樹」，它的原理（為什麼位置 i 的孩子在 2i + 1、2i + 2，siftDown 為什麼這樣寫）會在第 16 章「樹」仔細學，這裡先看它怎麼用來排序：\n1. 先把整個陣列整理成最大堆積（第一個迴圈），最大的會跑到 a[0]。\n2. 把 a[0]（最大的）跟最後一格交換，最大的就排好了；最後一格不算了，剩下的用 siftDown 再整理一次，又變回最大堆積。\n一直重複，就由小到大排好。看陣列下面的標記：last 右邊的格子是已經排好的部分；i 和 big 是 siftDown 正在比的位置。",
  code:FN(["void siftDown(int a[], int n, int i) {  // 讓 a[i] 往下沉到對的位置","    int left, right;  // 左孩子 2i + 1、右孩子 2i + 2","    int big;          // i 和兩個孩子裡，最大的在哪","    int t;            // 交換用","","    while (2 * i + 1 < n) {","        left = 2 * i + 1;","        right = 2 * i + 2;","        big = i;","        if (a[left] > a[big]) {","            big = left;","        }","        if (right < n && a[right] > a[big]) {","            big = right;","        }","        if (big == i) {","            break;  // 比兩個孩子都大，不用再沉了","        }","        t = a[i];","        a[i] = a[big];","        a[big] = t;","        i = big;","    }","}"],"int a[7] = {4, 10, 3, 5, 1, 8, 2};  // 要排序的數字","int n = 7;                         // 有幾個","int start;                         // 建堆積：從哪一個父親開始往下沉","int last;                          // 堆積現在的最後一格","int t;                             // 交換用","int i;                             // 印出來用","","for (start = n / 2 - 1; start >= 0; start--) {  // 1. 先建好最大堆積","    siftDown(a, n, start);","}","for (last = n - 1; last > 0; last--) {  // 2. 最大的換到最後，再往下沉","    t = a[0];","    a[0] = a[last];","    a[last] = t;","    siftDown(a, last, 0);","}","for (i = 0; i < n; i++) {","    cout << a[i] << \" \";","}","cout << endl;"),input:null,markers:{"a": ["last", "i", "big"]},
  predict:"第一次交換以後，最後一格是哪個數字？",
  ask:"siftDown(a, last, 0) 的第二個參數為什麼是 last，不是 n？"},
 {id:"14-8",title:"C++ 內建的 sort",isNew:"#include <algorithm>：sort(a, a + n)、greater<int>() 由大到小",uses:"陣列、vector",
  goal:"上面的方法都是自己寫的。C++ 已經內建了排序：#include <algorithm> 之後，sort(a, a + n) 就把陣列 a 的前 n 個由小到大排好；vector 要寫 sort(v.begin(), v.end())。\n想要由大到小，加上第三個參數 greater<int>()。sort 用的方法很快（大約 n log n），比泡沫、選擇、插入排序快很多，寫題目的時候通常直接用它。",
  code:M("int a[6] = {5, 2, 4, 6, 1, 3};      // 一個陣列","vector<int> v = {30, 10, 20};      // 一個 vector","int i;                             // 印出來用","","sort(a, a + 6);","for (i = 0; i < 6; i++) {","    cout << a[i] << \" \";","}","cout << endl;","sort(v.begin(), v.end(), greater<int>());  // 由大到小","for (int x : v) {","    cout << x << \" \";","}","cout << endl;").replace("#include <iostream>","#include <iostream>\n#include <algorithm>\n#include <vector>"),input:null,
  predict:"sort(a, a + 6) 一步就排好了。由大到小排的 v 會印出什麼？",
  ask:"把 sort(a, a + 6) 改成 sort(a, a + 3)，會排到哪幾格？"},
 {id:"14-9",title:"排序方法比一比",isNew:"O(n²) 和 O(n log n) 差多少",uses:"14-1 的時間複雜度",
  goal:"這一章的排序方法，時間複雜度大致是：\n泡沫、選擇、插入排序：O(n²)（兩層迴圈）。\n合併排序、堆積排序：O(n log n)（堆積排序的原理在第 16 章「樹」）。快速排序：平常是 O(n log n)，最差的時候（例如每次都選到最大或最小的當基準）會變成 O(n²)。C++ 的 sort：O(n log n)。\nlog n 是「n 一直除以 2，除幾次會變成 1」。n 是 100 萬的時候，log n 只有大約 20。這支程式幫你算出 n² 和 n log n 差多少。",
  code:M("long long n;   // 資料有幾個","long long t;   // 用來算 log n：一直除以 2","int lg;        // log n 大約是多少","","n = 10;","while (n <= 1000000) {","    lg = 0;","    t = n;","    while (t > 1) {","        t = t / 2;","        lg = lg + 1;","    }","    cout << \"n = \" << n << \"：n² = \" << n * n << \"，n log n = \" << n * lg << endl;","    n = n * 10;","}"),input:null,
  predict:"n = 100 萬的時候，n² 大約是 n log n 的幾倍？",
  ask:"如果 OJ 一秒大約能做 1 億次，n = 100 萬時，O(n²) 的排序大約要幾秒？O(n log n) 呢？"}
]});
