/* ---------- 第 15 章 搜尋：線性搜尋、二分搜尋、邊界、內建函式、二分搜答案 ---------- */
CHAPTERS.push({part:"進階程式設計",id:15,title:"搜尋",lessons:[
 {id:"15-1",title:"線性搜尋：一個一個找",isNew:"從頭看到尾，最多要看 n 個：O(n)",uses:"陣列、for、break",
  goal:"要在陣列裡找一個數字，最直接的方法就是從第 0 格開始一個一個看，找到就停。這叫做線性搜尋。\n資料不用排序就能用，但運氣不好（要找的在最後面，或根本沒有）就要把 n 個全部看完，時間複雜度是 O(n)。",
  code:M("int a[8] = {7, 3, 9, 1, 8, 2, 6, 4};  // 沒有排序的資料","int n = 8;      // 有幾個","int x = 8;      // 要找的數字","int i;          // 正在看第幾格","int pos = -1;   // 找到的位置，-1 代表還沒找到","","for (i = 0; i < n; i++) {","    if (a[i] == x) {","        pos = i;","        break;","    }","}","cout << pos << endl;"),input:null,markers:{"a": ["i"]},
  predict:"找 8 的時候，要看幾格才找到？",
  ask:"把 x 改成 5（陣列裡沒有 5），會看幾格？印出什麼？"},
 {id:"15-2",title:"二分搜尋：每次砍一半",isNew:"資料要先排好；看中間，再丟掉不可能的那一半：O(log n)",uses:"while、整數除法",
  goal:"如果資料已經由小到大排好，就可以更快：每次看「還沒排除的範圍」的正中間 a[mid]。\na[mid] 剛好是 x：找到了。a[mid] 比 x 小：x 只可能在右半邊，左半邊（含 mid）全部丟掉，l = mid + 1。a[mid] 比 x 大：丟掉右半邊，r = mid - 1。\n每次都丟掉一半，8 個最多看 4 次，100 萬個也只要看大約 20 次，時間複雜度是 O(log n)。",
  code:M("int a[8] = {1, 2, 3, 4, 6, 7, 8, 9};  // 已經由小到大排好","int n = 8;          // 有幾個","int x = 7;          // 要找的數字","int l = 0, r = n - 1;  // 還沒排除的範圍：a[l] ～ a[r]","int mid;            // 正中間","int pos = -1;       // 找到的位置，-1 代表沒找到","int times = 0;      // 看了幾次","","while (l <= r) {","    times = times + 1;","    mid = (l + r) / 2;","    if (a[mid] == x) {","        pos = mid;","        break;","    } else if (a[mid] < x) {","        l = mid + 1;  // x 在右半邊","    } else {","        r = mid - 1;  // x 在左半邊","    }","}","cout << pos << \" \" << times << endl;"),input:null,markers:{"a": ["l", "mid", "r"]},
  predict:"找 7 要看幾次？第一次看的是哪一格？",
  ask:"如果要找的數字很多個，二分搜尋找到的一定是第一個嗎？（15-4 會講）"},
 {id:"15-3",title:"找不到的時候",isNew:"l 和 r 越靠越近，最後交錯（l > r）就代表找不到",uses:"15-2 的二分搜尋",
  goal:"要找的數字不在陣列裡，二分搜尋一樣每次丟掉一半，範圍越來越小，最後 l 會跑到 r 的右邊（l > r），範圍裡一個都不剩，迴圈就停了，pos 還是 -1。\n停下來的時候，l 剛好指著「x 應該插進去的位置」：左邊的都比 x 小，從 l 開始都比 x 大。所以找不到也不是白找，還知道它該放在哪裡。",
  code:M("int a[8] = {1, 2, 3, 4, 6, 7, 8, 9};  // 已經由小到大排好","int n = 8;          // 有幾個","int x = 5;          // 要找的數字：不在陣列裡","int l = 0, r = n - 1;  // 還沒排除的範圍：a[l] ～ a[r]","int mid;            // 正中間","int pos = -1;       // 找到的位置，-1 代表沒找到","","while (l <= r) {","    mid = (l + r) / 2;","    if (a[mid] == x) {","        pos = mid;","        break;","    } else if (a[mid] < x) {","        l = mid + 1;","    } else {","        r = mid - 1;","    }","}","if (pos == -1) {","    cout << \"找不到 \" << x << \"，它應該插在第 \" << l << \" 格\" << endl;","} else {","    cout << \"在第 \" << pos << \" 格\" << endl;","}"),input:null,markers:{"a": ["l", "mid", "r"]},
  predict:"找 5 的時候，迴圈結束時 l 和 r 分別是多少？",
  ask:"把 x 改成 0（比全部都小）和 10（比全部都大），l 最後分別是多少？"},
 {id:"15-4",title:"二分搜尋的邊界",isNew:"找「第一個 ≥ x」：l < r、r = mid、l = mid + 1",uses:"15-2 的二分搜尋",
  goal:"有重複的數字時，常常要找「第一個 ≥ x 的位置」。這時候寫法要很小心：\n1. 範圍是 [l, r)：l 可能是答案，r 不是。r 一開始是 n，代表「全部都比 x 小」。\n2. a[mid] ≥ x：mid 可能就是答案，不能丟，r = mid。a[mid] < x：mid 一定不是答案，l = mid + 1。\n3. 迴圈條件是 l < r，最後 l 和 r 會碰在一起，那裡就是答案。\n二分搜尋最常寫錯的就是這些邊界：少一個 + 1，就可能變成無窮迴圈。",
  code:M("int a[8] = {1, 3, 3, 3, 5, 7, 8, 9};  // 由小到大排好，有重複","int n = 8;          // 有幾個","int x = 3;          // 要找第一個 ≥ x 的位置","int l = 0, r = n;   // 答案在 [l, r) 裡；r = n 代表全部都比 x 小","int mid;            // 正中間","","while (l < r) {","    mid = (l + r) / 2;","    if (a[mid] >= x) {","        r = mid;      // mid 可能就是答案，留著","    } else {","        l = mid + 1;  // mid 太小，一定不是答案","    }","}","cout << l << endl;"),input:null,markers:{"a": ["l", "mid", "r"]},
  predict:"a 裡面有三個 3，程式會找到哪一個 3 的位置？",
  ask:"把 l = mid + 1 改成 l = mid，會發生什麼事？試試看，想想為什麼。"},
 {id:"15-5",title:"C++ 內建的二分搜尋",isNew:"#include <algorithm>：binary_search、lower_bound、upper_bound",uses:"15-4、陣列、vector",
  goal:"C++ 已經內建了二分搜尋（資料一樣要先排好）：\nbinary_search(a, a + n, x)：有沒有 x，回傳 true 或 false。\nlower_bound(a, a + n, x)：第一個 ≥ x 的位置，就是 15-4 自己寫的那個。\nupper_bound(a, a + n, x)：第一個 > x 的位置。\n它們回傳的是「位置」（指標），減掉 a 就是第幾格。vector 要寫 v.begin()、v.end()，減掉 v.begin()。\n找不到的時候：binary_search 回傳 false（印出來是 0）；lower_bound 回傳 x 應該插進去的位置，如果全部都比 x 小，就是結尾（a + n，減掉 a 等於 n）。",
  code:M("int a[8] = {1, 3, 3, 3, 5, 7, 8, 9};  // 由小到大排好","vector<int> v = {2, 4, 6, 8};        // 由小到大排好","int pos;  // 找到的位置","","cout << binary_search(a, a + 8, 5) << endl;  // 有沒有 5？","pos = lower_bound(a, a + 8, 3) - a;           // 第一個 ≥ 3","cout << pos << endl;","pos = upper_bound(a, a + 8, 3) - a;           // 第一個 > 3","cout << pos << endl;","pos = lower_bound(v.begin(), v.end(), 5) - v.begin();","cout << pos << endl;","cout << binary_search(a, a + 8, 6) << endl;  // 找不到 6：0（false）","pos = lower_bound(a, a + 8, 10) - a;          // 全部都比 10 小","cout << pos << endl;").replace("#include <iostream>","#include <iostream>\n#include <algorithm>\n#include <vector>"),input:null,
  predict:"lower_bound 和 upper_bound 找 3，分別會回傳第幾格？找 10 呢？",
  ask:"upper_bound 的結果減掉 lower_bound 的結果，會得到什麼？那代表什麼意思？"},
 {id:"15-6",title:"二分搜答案",isNew:"答案「可以 / 不行」有分界的時候，可以對答案做二分搜尋",uses:"15-2 的二分搜尋",
  goal:"二分搜尋不只能在陣列裡找數字，也能「找答案」。例如：找最大的整數 x，讓 x × x ≤ n。\n答案可能是 0 ～ n。猜一個 mid：如果 mid × mid ≤ n，mid 可以，答案至少是 mid，試試更大的（l = mid + 1）；如果 mid × mid > n，mid 太大，答案比較小（r = mid - 1）。\n只要答案有「小的都可以、大的都不行」這種分界，就能這樣每次砍一半，不用從 0 一個一個試。",
  code:M("int n = 50;         // 找最大的 x，讓 x × x ≤ n","int l = 0, r = n;   // 答案在 l ～ r 之間","int mid;            // 這一次猜的答案","int ans = 0;        // 目前找到可以的答案","","while (l <= r) {","    mid = (l + r) / 2;","    if (mid * mid <= n) {","        ans = mid;    // mid 可以，記下來","        l = mid + 1;  // 試試更大的","    } else {","        r = mid - 1;  // mid 太大","    }","}","cout << ans << endl;"),input:null,
  predict:"n = 50 的時候，答案是多少？第一次猜的 mid 是多少？",
  ask:"如果從 0 開始一個一個試，n = 50 要試幾次？二分搜答案試了幾次？"},
 {id:"15-7",title:"線性搜尋和二分搜尋比一比",isNew:"O(n) 和 O(log n)：n 越大差越多",uses:"14-1 的時間複雜度、15-1、15-2",
  goal:"線性搜尋最多要看 n 個，是 O(n)；二分搜尋每次砍一半，最多看大約 log n 次，是 O(log n)。\nn 小的時候差不多，n 一大差距就非常明顯。這支程式幫你算出不同的 n，兩種方法最多各要看幾次。\n不過二分搜尋有個前提：資料要先排好。如果只找一次，先排序（O(n log n)）反而比直接線性搜尋還慢；要找很多次的時候，先排序再二分搜尋才划算。",
  code:M("long long n;   // 資料有幾個","long long t;   // 用來算 log n：一直除以 2","int lg;        // 二分搜尋最多要看幾次","","n = 10;","while (n <= 1000000) {","    lg = 0;","    t = n;","    while (t > 0) {","        t = t / 2;","        lg = lg + 1;","    }","    cout << \"n = \" << n << \"：線性最多 \" << n << \" 次，二分最多 \" << lg << \" 次\" << endl;","    n = n * 10;","}"),input:null,
  predict:"n = 100 萬的時候，二分搜尋最多要看幾次？",
  ask:"如果一個題目要在 10 萬筆資料裡找 10 萬次，用線性搜尋大約要做幾次？會不會 TLE？"}
]});
